### ISSUE TITLE
[FEATURE]如果源站点无法获取豆瓣链接，显示获取豆瓣简介按钮

### ISSUE THREAD

**Issue by fishmanfishing** [techmovie/easy-upload#108]
**为了更好地了解问题，请填写以下信息**
* easy-upload版本：2.1.0

**问题描述**
原帖的豆瓣链接不在简介里但有单独的项目有链接 转发的时候不能自动获取到
例如：原帖 https://hdhome.org/details.php?id=86452&hit=1 转发到有豆瓣链接的网站比如 杜比 高清视界 猫 南洋 北洋 等

**问题截图**
原帖 ![photo_2021-05-25_21-51-03](https://user-images.githubusercontent.com/84783414/119512342-cd817900-bda5-11eb-9294-f624493c4a70.jpg)
转发时 ![photo_2021-05-25_21-51-08](https://user-images.githubusercontent.com/84783414/119512421-de31ef00-bda5-11eb-93a0-e4b2d7c03384.jpg)

**Comment by techmovie** [comment]
@fishmanfishing 这个种子里我没看到豆瓣链接呀？

**Comment by kidgokugoku** [comment]
@fishmanfishing 你转种之前自己把豆瓣链接编辑到简介里就可以了

**Comment by techmovie** [comment]
@kidgokugoku 这个种子源站点也没有豆瓣链接吧？如果是这种情况就不做支持了

**Comment by techmovie** [comment]
改成Feature了,后续有时间再做支持。
