### ISSUE TITLE
[FEATURE]其他图床

### ISSUE THREAD

**Issue by rty813** [techmovie/easy-upload#123]
**这个功能是否与某个问题相关**

否
**描述你的期望功能**
能否添加其他图床的支持？目前一键转种以后，图片都无法转过去，而像我这种没有ptpimg账号的，需要手动把原种网页上的图片下载到本地，然后再上传到一些免费图床，然后再在转种的网页上添加上，感觉很麻烦

**描述你的替代方案**
用一些其他图床代替ptpimg

**额外信息**

**Comment by ted423** [comment]
@rty813 比如哪些图床？支持api上传啥的

**Comment by rty813** [comment]
我对图床了解不是很多，我举个例子，参考一下：
花瓣网

接口：https://huaban.com/upload/
请求方式：POST
表单name：upload1

**Comment by rty813** [comment]
我对图床了解也不是很多，sm.ms可以吗？这个是有API的
[https://doc.sm.ms/](url)

**Comment by rty813** [comment]
还有个叫imgur的，也可以api上传。

**Comment by techmovie** [comment]
@rty813 sm.ms只能上传5MB以内的图片，imgur获取token又比较麻烦，这两个都不太适合。

**Comment by rty813** [comment]
5MB还可以吧，我在TCCF上面发种，上传图片都是限制在512KB以内的。可否作为一个选择呢？其实大多数图片也都几百KB，偶尔有很大的图片，也可以让用户自己去用其他方法。

**Comment by techmovie** [comment]
@rty813 随便一张重编码的截图都会超过5M吧，我会找一个合适的图床的。另外，你是哪个站需要自己下载下来再上传的？

**Comment by rty813** [comment]
北洋园转到TCCF，TCCF无法显示图片。

**Comment by ted423** [comment]
@techmovie 源截图的话会超，播放器截可能不会

**Comment by rty813** [comment]
我是觉得如果能找到合适的图床最好，如果没有的话，这种5M的也可以考虑加入，毕竟也是个选择。因为我目前转的种子大都是教育类资源，没有什么大图，都是几百KB的。

**Comment by rty813** [comment]
我转了转HDSKY里面的一些4K蓝光原盘种子页，里面的图片最大也就2、3M左右，所以我感觉问题不大吧

**Comment by techmovie** [comment]
@rty813 正常应该是二三十兆吧

**Comment by rty813** [comment]
> @rty813 正常应该是二三十兆吧

![image](https://user-images.githubusercontent.com/22488813/123412166-de5f1d80-d5e3-11eb-898a-beb90c020672.png)
![image](https://user-images.githubusercontent.com/22488813/123412225-f2a31a80-d5e3-11eb-844d-7d8f199e6cff.png)

我这是随便找了两个置顶的4K蓝光原盘种子详情页，里面除了动图以外，最大的也就1、2M左右

**Comment by ted423** [comment]
@rty813 有些站要求的是原图，你说的1-2M要么就是1080p的，要么就是有损jpg,我倾向于前者

**Comment by ted423** [comment]
@ted423 跑个题，github issue可能不要带站点域名截图啥的可能会比较好

**Comment by ted423** [comment]
如图 
![image](https://user-images.githubusercontent.com/7042766/123412773-91c81200-d5e4-11eb-9f10-1d3e96ce9504.png)

**Comment by rty813** [comment]
> @ted423 跑个题，github issue可能不要带站点域名截图啥的可能会比较好

哦哦 不好意思，我先hide了。
我的意思是，我现在已有的站点，很少有让上传原图的，也许是为了浏览更快。再贴一张mteam的截图，也是4K原盘，也没有上传原图：
![image](https://user-images.githubusercontent.com/22488813/123413030-db186180-d5e4-11eb-8298-637dc967a9dd.png)

**Comment by ted423** [comment]
@rty813 但是要看站点要求，有些站会要求原图，4k先不谈，1080p有不少会超

**Comment by rty813** [comment]
我大概知道了。应该是因为在种子详情页看的时候，看的实际上是压缩后的图片。点进去以后，确实是原图，有5M以上

**Comment by rty813** [comment]
这就不太好办了，还是得指望大佬们看看能不能发掘更好用的图床了🤦‍💪

**Comment by rty813** [comment]
北洋园的图片应该也是可以外部访问的，我再试试吧，可能是我操作有问题

**Comment by techmovie** [comment]
决定用这个了 
https://gifyu.com/
