### ISSUE TITLE
[新站点] 蒲公英PT

### ISSUE THREAD

**Issue by rty813** [techmovie/easy-upload#125]
* 站点地址：http://npupt.com/
* 站点架构：NexusPHP
* 站点是否限制发布权限：无
* 站点发布种子所需的用户等级：无
* 邀请获取渠道：
> 蒲公英（NPUPT）
> 官方邀请入口：
> * 6V：上传量至少1TB，发表主题 >= 10
> 
> * BYR：上传量至少500GB
> 
> * DutPT: 只面向具有ipv6环境的高校学生
> 
> * HUDBT：用户等级要求PU以上且需要IPV6环境
> 
> * XJCT:上传量不低于500GB且分享率大于1
> 
> * MTPT：上传量至少500GB且分享率不低于1
> 
> * NYPT：1.必须为教育网IPv6用户,申请用户的等级需达到优秀硕士或上传200G以上或发种数在5个以上
> 
> * HD4Fans HDSky 烧包 PTerClub TCCF TJUPT
> 备注：申请者应来自高校等科研机构，有教育网IPv6地址。不在高校或科研机构者请勿申请

如果需要，我可以发邀

* 其他信息：

**Comment by techmovie** [comment]
@rty813 需要校园网IPV6访问么？我打不开

**Comment by techmovie** [comment]
@rty813 不浪费邀请了 直接把上传页的html文件发我吧

**Comment by rty813** [comment]
公网IPv6可以访问。
[蒲公英PT站 __ 发布 NPUBits - Powered by NPUBits.zip](https://github.com/techmovie/easy-upload/files/6723919/PT.__.NPUBits.-.Powered.by.NPUBits.zip)

**Comment by techmovie** [comment]
html文件没办法用，方便的话发我个邀请吧。

**Comment by rty813** [comment]
> html文件没办法用，方便的话发我个邀请吧。

实在不好意思，蒲公英PT邮件系统故障，暂时无法发送邀请。

**Comment by imalkaid** [comment]
蒲公英注册需要校园网环境才行

**Comment by rty813** [comment]
> 蒲公英注册需要校园网环境才行

注册需要教育网邮箱。
登陆的话，公网IPv6就可以。
