### ISSUE TITLE
[新站点]各类音乐站

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#127]
* 站点地址：
* 站点架构：
* 站点是否限制发布权限：
* 站点发布种子所需的用户等级：
* 邀请获取渠道：
* 其他信息：

**Comment by ted423** [comment]
红 /wiki.php?action=article&id=455

**Comment by ted423** [comment]
一个可供参考的GZ转NP的
标题可能会稍微有点问题
红/torrents.php?id=18186&torrentid=112571#torrent112571
MT/details.php?id=559628

红/torrents.php?id=583927&torrentid=1520508#torrent1520508
MT/details.php?id=559629

**Comment by techmovie** [comment]
@ted423 CD - FLAC - Lossless  这个放在副标题里是不是更合适

**Comment by ted423** [comment]
@techmovie 因为直接读的红的种子名🌚

**Comment by techmovie** [comment]
初步支持了部分国内站点的转入，部分站点没有账号，也有些要填入的东西有点多，先放弃了

**Comment by ted423** [comment]
gz到gz的话，一般用json就可以，因为涉及到文件操作，感觉脚本其实不太合适。（而且操作起来还挺方便的）
就我个人看来，需要发布者重复劳动的转载模式其实是有一定问题的。所以一些不支持也没事。
另外比较重要的就是这个信息 Walt Disney Records / D002425302 / CD
不过可以以后我来改改看（习惯摸鱼的人表示）

**Comment by ted423** [comment]
不过有这么个脚本 https://gitlab.com/cheesegoat/orpheus-populator
