### ISSUE TITLE
[FEATURE]Blutopia requires bbcode to resize images for site display

### ISSUE THREAD

**Issue by Audionut** [techmovie/easy-upload#128]
**Is your feature request related to a problem? Please describe.**
Blutopia requires bbcode to resize images for site display

**Describe the solution you'd like**
[img=400]img_path.png[/img]

With "=400" being the addition required.

**Comment by techmovie** [comment]
@Audionut Have you tried to convert the thumbnails first?

**Comment by Audionut** [comment]
I don't think I understand entirely what you mean, but it sounds like it defeats the purpose.

Most of the images from PTP > BHD get this treatment.

`[url=https://ptpimg.me/5p3342.png][img=350x350]https://ptpimg.me/5p3342.png[/img][/url]`

Which is what this dumb user would expect. As it brings automation to the process of easy-uploading.

**Comment by techmovie** [comment]
@Audionut got it
