### ISSUE TITLE
[新站点]北邮人BYRPT

### ISSUE THREAD

**Issue by wy-luke** [techmovie/easy-upload#129]
* 站点地址：https://bt.byr.cn/
* 站点架构：BYRBT 2012-2021 Powered by NexusPHP
* 站点是否限制发布权限：否
* 站点发布种子所需的用户等级：Elite User及以上等级的用户可直接发布种子，无需经过候选。Peasant或以上等级的用户可以添加候选。
* 邀请获取渠道：高校注册，邀请
* 其他信息：仅IPV6访问，是教育网的pt，作者应该也知道，是个大站。如果楼主访问不方便，我可以配合。谢谢作者做了好软件❤

**Comment by techmovie** [comment]
@wy-luke 才发现北邮不支持BBCode😂 还得再改下

**Comment by techmovie** [comment]
> @wy-luke 才发现北邮不支持BBCode😂 还得再改下

fixed in https://github.com/techmovie/easy-upload/commit/736a235e0e7d328a81b502a20924eb5238d537af
