### ISSUE TITLE
[新站点] AsianDVDClub

### ISSUE THREAD

**Issue by dibin666** [techmovie/easy-upload#130]
* 站点地址：https://asiandvdclub.org/
* 站点架构：有点像NexusPHP，但不完全是
* 站点是否限制发布权限：无
* 站点发布种子所需的用户等级：无
* 邀请获取渠道：目前开放注册
* 其他信息：支持互转

**Comment by techmovie** [comment]
@dibin666 暂不考虑支持，先关了，后续等站点发展稳定后再重新打开。
