### ISSUE TITLE
[BUG] Clicks doesn't register on Settings button

### ISSUE THREAD

**Issue by Purfview** [techmovie/easy-upload#132]
I see the animated button is back, and this bug is back again.

Sometimes clicks doesn't register on the settings button. At first I thought that it's broken, but after ~5 clicks or so click registered.
It's random, sometimes you click 10 times and 10 times it will open settings, sometimes only from 5th time click registers.

**Comment by techmovie** [comment]
Still can't reproduce this issue. Closed for now.
