### ISSUE TITLE
[BUG] Aither种子页面不显示脚本

### ISSUE THREAD

**Issue by dibin666** [techmovie/easy-upload#135]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Google Chrome
* 浏览器版本：91.0.4472.124
* 所用用户脚本扩展名称： Tampermonkey 
* easy-upload版本：2.2.7

**问题描述**
Aither失效了，种子页面不显示脚本

**复现步骤**
无

**问题截图**

**Comment by techmovie** [comment]
@dibin666 我没账号了 帮忙看下是不是改的跟blu一样了
