### ISSUE TITLE
[BUG] "Quick search" overlaps with the listed trackers

### ISSUE THREAD

**Issue by newadventure079** [techmovie/easy-upload#152]
* Browser：Microsoft Edge
* Browser Version ：Version 99.0.1141.0 (Official build) Dev (arm64)
* Script manager extension[e.g. tampermonkey Violentmonkey]：Violentmonkey
* easy-upload version：3.03

**Describe the bug**
The string "Quick search" overlaps with the listed trackers

**To Reproduce**
View the string "Quick search" on the easy-upload widget

**Expected behavior**
No overlapping should occur

**Screenshots**
![Screen Shot 2022-01-30 at 1 58 29 AM](https://user-images.githubusercontent.com/84156407/151693421-c0e33ca7-aef3-4568-9470-95df27ae518e.jpg)

**Comment by techmovie** [comment]
@newadventure079 Which site?

**Comment by newadventure079** [comment]
@techmovie That screenshot is from PTP

**Comment by newadventure079** [comment]
@techmovie I found another one.  This one is on EMP

![Screen Shot 2022-01-30 at 6 44 55 PM](https://user-images.githubusercontent.com/84156407/151728298-e082bf64-677c-4d79-a983-bf831b72963a.jpg)
