### ISSUE TITLE
[BUG] Tracker is still being opened in a tab, even tho it was unchecked, when clicking Batch Transfer

### ISSUE THREAD

**Issue by newadventure079** [techmovie/easy-upload#153]
* Browser：Microsoft Edge
* Browser Version ：Version 99.0.1141.0 (Official build) Dev (arm64)
* Script manager extension[e.g. tampermonkey Violentmonkey]：Violentmonkey
* easy-upload version：3.03

**Describe the bug**
My "Transfer to" is set up with 2 trackers: BHD and SC.  It used to be BHD, SC and KG.  I removed KG from both the search and the transfer in the settings.  Now only BHD and SC are listed.  When I click on Batch Transfer, tabs for BHD, SC and KG open. KG shouldn't open anymore.

**To Reproduce**
Enable BHD, SC and KG for transfer
Click Batch transfer and see all 3 of them open in new tabs
Go into settings and unselect KG and save
See that only BHD and SC are now listed
Click Batch transfer again
Tabs for BHD, SC and KG will open

**Expected behavior**
Only tabs for the trackers that I have as checked in the settings should Batch transfer

**Screenshots**
The 3 tabs that opened:
![Screen Shot 2022-01-30 at 2 18 58 AM](https://user-images.githubusercontent.com/84156407/151693964-8abd17b5-b473-4b9c-8abd-d20cb85ff160.jpg)

**Additional context**
I've refreshed the page and even closed my browser and it still happen. I dont know if I need to clear my localStorage or what.  I thought I'd report this in case something isn't being deleted when it should.

**Comment by techmovie** [comment]
![image](https://user-images.githubusercontent.com/59314774/151694016-5a01c3ea-1514-41eb-9bef-86a21f78c5c3.png)

**Comment by newadventure079** [comment]
Ah oops, I unchecked it from the search and transfer but didn't scroll far enough down to see the 'batch transfer' section
