### ISSUE TITLE
[FEATURE] Add Batch search button

### ISSUE THREAD

**Issue by newadventure079** [techmovie/easy-upload#154]
**Is your feature request related to a problem? Please describe.**
The links next to Quick search are not clickable with the middle mouse button, therefore, you cannot open each of the tabs in the background in succession.  You have to click one, get taken to a new tab, go back, click another link, get taken to a new tab, etc.  You can't quickly search all at once

**Describe the solution you'd like**
A button just like the Batch transfer, but will be named Batch search and will open all the search links at once

**Describe alternatives you've considered**
Middle clicking the search links to have them load in the background but that wasn't possible

**Additional context**
![Screen Shot 2022-01-30 at 1 37 49 PM](https://user-images.githubusercontent.com/84156407/151717004-ac15a3dd-9426-451c-9803-de5f0900cb63.jpg)

**Comment by newadventure079** [comment]
I filled out the template correctly.  Please re-open

**Comment by newadventure079** [comment]
@techmovie Can you re-open this? I dont know what I did wrong to not fill it out correctly

**Comment by ted423** [comment]
@newadventure079 may because you delete something

**Comment by newadventure079** [comment]
I dont remember removing anything.  I double checked with a blank template and it looks identical

**Comment by newadventure079** [comment]
There might be a bug in the bot lol

**Comment by newadventure079** [comment]
I just saw this at `https://github.com/techmovie/easy-upload/wiki/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B`
```
IF YOU CLICK "QUICK SEARCH" ON THE FAR LEFT, YOU CAN SEARCH IN BULK FOR THE PRESENCE OF THE SAME SEED IN ALL NP SITES. RED REPRESENTS NON-EXISTENCE AND GREEN REPRESENTS EXISTENCE.
```
![68747470733a2f2f707470696d672e6d652f3434373564302e676966](https://user-images.githubusercontent.com/84156407/151747047-4a27921f-7488-40a7-bb20-2a4d416b3144.gif)

I tried that and clicked the Quick search link but nothing happened

**Comment by techmovie** [comment]
@newadventure079 Just support Nexus sitez
