### ISSUE TITLE
[New Site] Cinemageddon

### ISSUE THREAD

**Issue by newadventure079** [techmovie/easy-upload#157]
* URL：https://cinemageddon.net/index.php
* Site based on[e.g. Gazelle UNIT3D]：unknown
* Whether the site restricts publishing rights：No
* The user level required for the site to publish new torrent：Any
* Where to get an invite：Some private tracker invite forums

* Additional text：

**Comment by techmovie** [comment]
If send me the upload page HTML files will be better.
