### ISSUE TITLE
[BUG]音频视频编码相关

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#164]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-upload版本：3.1.0

**问题描述**
如果我没弄错的话audioCodec 前面ac3 dd这些应该是脚本自身判断用的，我看wiki里也没有做说明
但是dd和ac3是完全相同的，可以进行合并
再有就是h265以及hevc，虽然h265不等于hevc，并且有些站可能会用h265/x265区分原盘以及压制（但我好像还没遇到），并且pt站里应该也没有其他格式的265，所以我认为h265和hevc应该也可以合并。

另外 这个看不懂，hdh里好像也没mpeg4
```
       mpeg4:
          - '5'
          - '412'
          - '418'
          - '426'
          - '433'
          - '445'
```
**复现步骤**

**问题截图**

**Comment by techmovie** [comment]
@ted423 现在还真不好合并。比如A站拿到的是DD B站又是AC3 两个站转载到C站的时候两个就要统一适配到一个选项里。H265也是一样。hdh里有ipad所以加了个mpeg4

**Comment by ted423** [comment]
> @ted423 现在还真不好合并。比如A站拿到的是DD B站又是AC3 两个站转载到C站的时候两个就要统一适配到一个选项里。H265也是一样。hdh里有ipad所以加了个mpeg4

拿的时候应该也可以合并？这个拿指的是直接从文件标题截取还是？

ipad指的这个？
![image](https://user-images.githubusercontent.com/7042766/153537186-bc898c8c-81df-4dee-8f67-cecd311a0a9c.png)

**Comment by techmovie** [comment]
@ted423 有些是标题拿 有一些是直接从参数栏那里取(主要是内站)。

**Comment by ted423** [comment]
被啪啪打脸
https://猫/forums.php?action=viewtopic&topicid=6369
tg管理说的
h265这个东西，大家交流的时候用来说明非x265的编码器
目前猫站是要求web-dl用H265(还是H.265忘了)，BD才准用HEVC

不知道脚本以后实现自动转换还是丢给用户自己头疼

**Comment by techmovie** [comment]
@ted423 脚本需要做的是根据webdl还是BD区分下该选择HEVC还是H265？

**Comment by ted423** [comment]
@techmovie 很多web-dl原发布标题会写hevc,但猫站统一标题要写H265现在。
