### ISSUE TITLE
[BUG]瓷 演唱会转mt变成 电影

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#168]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* easy-upload版本：

**问题描述**

**复现步骤**

**问题截图**

**Comment by ted423** [comment]
试了下转猫站也有问题，但是mv没问题，所以应该是source端不认演唱会(Vocal Concert)这个分类

**Comment by ted423** [comment]
@ted423 调试的时候发现到了种子详情，而MV这块是正常的获取到了分类

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/153819771-027145ca-3f9f-4347-ba3d-e8609da5e8dc.png)

**Comment by techmovie** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/59314774/153822307-e51a6f1d-3e66-4485-8eb2-f137ed86000f.png">
这里分类获取错了

**Comment by ted423** [comment]
> 

我调试看的NP那个ts，分类读到种子详情那了，不知道哪的问题，代码看不懂，但是MV的页面读取又能正常读取到分类

**Comment by techmovie** [comment]
现在SourceMap有点问题 定位错地方了
