### ISSUE TITLE
[FEATURE]导入导出配置或者可以编辑配置文件

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#171]
### 是否有重复的issue?

- [X] 我已经检索过相关issue

### 这个功能是否与某个问题相关

感觉最近重点了N次配置，特别是我有两台电脑

### 描述你的期望功能

GM 有个 GM_registerMenuCommand 可以这样
![image](https://user-images.githubusercontent.com/7042766/153973310-446a657e-3c8b-4b76-99ae-cd71fcf1552d.png)
![image](https://user-images.githubusercontent.com/7042766/153973363-183ffce2-5227-4dd8-a587-ce7888be237f.png)
或者导入导出？

### 描述你的替代方案

或者导入导出？

**Comment by techmovie** [comment]
没想出好的恢复备份的方案 先不做了。
可以通过脚本管理插件自带的功能来管理。
全选后复制粘贴就可以了。
tampermonkey：
<img width="474" alt="image" src="https://user-images.githubusercontent.com/59314774/155845203-1715f40d-30f9-48da-9b03-540ef5c7dc51.png">
暴力猴：
<img width="426" alt="image" src="https://user-images.githubusercontent.com/59314774/155845209-2b4a3865-d706-43b6-9f35-864dde0d25e4.png">

**Comment by ted423** [comment]
> 没想出好的恢复备份的方案 先不做了。 可以通过脚本管理插件自带的功能来管理。 全选后复制粘贴就可以了。 tampermonkey： <img alt="image" width="474" src="https://user-images.githubusercontent.com/59314774/155845203-1715f40d-30f9-48da-9b03-540ef5c7dc51.png"> 暴力猴： <img alt="image" width="426" src="https://user-images.githubusercontent.com/59314774/155845209-2b4a3865-d706-43b6-9f35-864dde0d25e4.png">

居然还有这么个东西！
