### ISSUE TITLE
[FEATURE] 增加MutationObserver或类似的功能？

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#175]
### 是否有重复的issue?

- [X] 我已经检索过相关issue

### 这个功能是否与某个问题相关

BHD添加种子时会回写，例如1080p的原盘会自动把type变成1080p,标题也会变。

月月也会

月月目前使用了打开torrents列打开种子的不刷新加载，导致没法加载easy-upload(不过目前不需要修改，因为他们目前在折腾新界面)

### 描述你的期望功能

MutationObserver，在添加种子后再填写信息之类的

### 描述你的替代方案

无

**Comment by techmovie** [comment]
@ted423 可以的 现在有些站点我是通过移除种子DOM监听事件的办法实现的

**Comment by techmovie** [comment]
看了下MutationObserver的API，不支持监听表单value的变化。issue先开着 后面解决下BHD的问题

**Comment by ted423** [comment]
试了一下
```
Object.defineProperty(document.querySelector("#autotype option[value='1080p']"),'selected',{
set: function(){console.log('BHD change remove by Easy-upload')}
})

Object.defineProperty(document.querySelector("#autotype option[value='Null']"),'selected',{
set: function(){console.log('BHD change remove by Easy-upload')}
})
```
这个把BHD的修改干掉了，不过会卡在Select(看起来BHD是先清然后再设置一遍，理论上可以setter 1080p和2160p做个再检测)

不过感觉这种不太具有美感，会破坏网页原生功能
不清楚这个会不会更好
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by ted423** [comment]
aither传了种子之后imdb 和 tmdb就消失了，大概也需要
还有预览后描述信息也会消失
https://github.com/techmovie/easy-upload/issues

**Comment by ted423** [comment]
```
$("#torrent").bind('change',function(){
console.log('uploaded torrent')
});
```
或许考虑可以这么写
