### ISSUE TITLE
[BUG] For KG, movie title does not contain the AKA title

### ISSUE THREAD

**Issue by newadventure079** [techmovie/easy-upload#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On KG, the title should be in the formation of `"Original Title AKA Best Known Title [Extra info if needed]"` (taken directly from their upload page).  

So a movie named `Danza macabra AKA Castle of Blood` should have the title `Danza macabra AKA Castle of Blood` but the title is entered as `Danza macabra`

### Expected Behavior

The title should contain the AKA name too.  ie. `Danza macabra AKA Castle of Blood`

### Steps To Reproduce

1. Pick any movie on PTP that has an AKA in the title
2. Upload it to KG
3. Notice how the title on KG is missing the "AKA" part

### Environment

```markdown
- Browser：Microsoft Edge
- Browser Version：Version 100.0.1190.0 (Official build) Canary (arm64)
- Script manager extension：Tampermonkey
- easy-upload version：3.1.8
```

**Comment by techmovie** [comment]
Title is filled by site automatically,I'm not sure if script have to handle this issue.
