### ISSUE TITLE
[BUG]HDatmos加载失败

### ISSUE THREAD

**Issue by zszczh** [techmovie/easy-upload#181]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

![捕获](https://user-images.githubusercontent.com/30950457/161195241-939de485-cea0-4ec8-8765-3859d5c047a2.JPG)
之前好像还正常，今天发现没显示转种的操作区域

### 期待表现

不知道我是不是单独的例子，如果是bug的希望能修复下

### 运行环境

```markdown
浏览器名称：Google Chrome
浏览器版本： 99.0.4844.84
Script manager extension：tampermonkey
easy-upload version：3.1.1
```

**Comment by techmovie** [comment]
@zszczh 考虑到这个站没啥原创资源 转出没做支持

**Comment by zszczh** [comment]
> @zszczh 考虑到这个站没啥原创资源 转出没做支持

好的，谢谢
