### ISSUE TITLE
[New Site] MoreThanTV

### ISSUE THREAD

**Issue by successorliver** [techmovie/easy-upload#182]
### URL

http://morethantv.me/

### Site based on

Gazelle

### Whether the site restricts publishing rights

Yes

### The user level required for the site to publish new torrent

Key Grip

### Where to get an invite

Tracker invite forums

**Comment by successorliver** [comment]
Transfer to not working for MTV

**Comment by techmovie** [comment]
@successorliver Don't have upload access.

**Comment by successorliver** [comment]
Can I upload the .php page here? If it helps?

**Comment by techmovie** [comment]
@successorliver Sure! Remeber delete any info realted to your account.
