### ISSUE TITLE
[新站点]hdatmos全景声（阿童木）

### ISSUE THREAD

**Issue by sandboxdream** [techmovie/easy-upload#195]
### 站点地址

https://hdatmos.club/

### 站点架构

NexusPHP

### 站点是否限制发布权限

是

### 站点发布种子所需的用户等级

User

### 邀请获取渠道

贴吧，或者网站本身的群聊区中发个邮箱后求邀都能有

### 其他

8g以上电影，蓝光，原盘等电影

**Comment by techmovie** [comment]
提issue前可以看一下当前已经的支持站点

**Comment by sandboxdream** [comment]
好吧，在阿童木上没看到传出页面就以为不支持了...
