### ISSUE TITLE
[BUG]更新了最新版本的UNIT3D站点无法预览描述

### ISSUE THREAD

**Issue by techmovie** [techmovie/easy-upload#196]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

更新了最新版本的UNIT3D站无法预览描述，且在预览后会丢失description

### 期待表现

正常预览

### 运行环境

```markdown
- 浏览器名称：Google Chrome
- 浏览器版本：104.0.5112.101 (Official Build) (arm64)
- 所用用户脚本扩展名称：Tampermonkey
- easy-upload版本：3.2.6
```

**Comment by techmovie** [comment]
暂无解决方案

**Comment by ted423** [comment]
https://laravel-livewire.com/docs/2.x/properties
感觉好像跟这个有关

**Comment by ted423** [comment]
```
document.querySelector('#bbcode-description').dispatchEvent(new Event('input'));
```
可以这么弄

**Comment by techmovie** [comment]
> ```
> document.querySelector('#bbcode-description').dispatchEvent(new Event('input'));
> ```
> 
> 可以这么弄

这个测试过了么 我记得这个也不行
