### ISSUE TITLE
[BUG]皮转NP img变成直连

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#199]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

[BUG]皮转NP img变成直连
/torrents.php?id=78613&torrentid=590102
BHD正常

### 期待表现

[img]http://ptpimg.me/5j0h4c.png[/img]
[img]http://ptpimg.me/16aaa7.png[/img]
[img]http://ptpimg.me/l8c78s.png[/img]

### 运行环境

```markdown
- 浏览器名称：cent browser
- 浏览器版本：版本 5.0.1002.182（正式版本） （64 位） (Chromium 102.0.5005.167)
- 所用用户脚本扩展名称：tampermonkey
- easy-upload版本：	3.2.10
```

**Comment by ted423** [comment]
怎么感觉好像是我的锅

**Comment by ted423** [comment]
看起来不是，源代码无bbcode

**Comment by techmovie** [comment]
https://github.com/techmovie/easy-upload/commit/9c178585d05bb78624960472cb0113a450129243
