### ISSUE TITLE
[BUG]HDT 的发种的一些待完善的地方

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#202]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

HDT Remux和原盘用  Blu-ray
encode 用BluRay

mediainfo 太长的话似乎不行
![image](https://user-images.githubusercontent.com/7042766/188623401-a2e5af51-b6d3-4609-8988-e37c2717803b.png)
Tech info (Use latest [Mediainfo](https://mediaarea.net/en/MediaInfo) to confer if no other is specified):
Blu-ray
     - [BDinfo](https://anonym.to/?https://www.videohelp.com/software/BDInfo) scan of the main playlist - copy of the "QUICK SUMMARY" is preferred, otherwise copy from "DISC INFO" to "SUBTITLES" included, do not dump all BDinfo scan!
Remux
     - Name
     - Runtime
     - Video properties: codec, bitrate, width, height, framerate
     - Audio properties: codec, bitrate, channels, language(s)
     - Subtitles: codec, language; None (if none available)
     - full, unedited log(s) from demuxing, preferably in hide BBcode is not mandatory but preferable.
Encodes
     - Name
     - Container
     - Runtime
     - Video properties: codec, bitrate, width, height, framerate
     - Audio properties: codec, bitrate, channels, language(s)
     - Subtitles: codec, language; - None (if none available)

### 期待表现

只是个笔记
特别是mediainfo
还没想好咋搞

### 运行环境

```markdown
- 浏览器名称：Cent Browser
- 浏览器版本：
- 所用用户脚本扩展名称：Tampermonkey
- easy-upload版本：3.2.11
```

**Comment by techmovie** [comment]
这个站有bug也不考虑修一修么😅

**Comment by ted423** [comment]
本人现在基本没去发了
