### ISSUE TITLE
[FEATURE]wiki 添加新站点的一些完善

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#211]
### 是否有重复的issue?

- [X] 我已经检索过相关issue

### 这个功能是否与某个问题相关

添加新站点的相关问题

### 描述你的期望功能

wiki中的search
seedDomSelector
相关说明不够完善
目前调试发现 https://github.com/techmovie/easy-upload/blob/1e56a7934916b11c59087e82db8a1ca102b81441/src/index.tsx#L40
这一部会决定是否添加 seed-dom

### 描述你的替代方案

目前发现speedapp里其实已经添加成功了本脚本的设置页面，但是 seed-dom没有被添加到 element

**Comment by ted423** [comment]
看起来还要改这个
https://github.com/techmovie/easy-upload/blob/master/src/components/Container.tsx

**Comment by techmovie** [comment]
重构过后改逻辑了 wiki没更新

**Comment by ted423** [comment]
提这个issue也考虑到如果有其他人想弄一些不在已有架构的站点可能会有个参考。
虽然也可能没有其他人

**Comment by techmovie** [comment]
已更新
