### ISSUE TITLE
[BUG]tv转载到u3d站无法获取到tmdb

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#216]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

感觉跟这里有关
https://github.com/techmovie/easy-upload/blob/00efdff2842bf39c0776b38211bdb667940add59/src/common.ts#L754

### 期待表现

支持

### 运行环境

```markdown
- 浏览器名称：cent
- 浏览器版本：
- 所用用户脚本扩展名称：
- easy-upload版本：
```

**Comment by techmovie** [comment]
剧集的imdbid是不是单集的id？

**Comment by ted423** [comment]
> 剧集的imdbid是不是单集的id？

剧集的imdb都是所有季一起那个
目前应该只有FXXS这个站弄单集imdbid
