### ISSUE TITLE
[BUG]朱雀的小问题[Done]

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#221]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

发种uhd disc会选到diy,估计是选择器选中了两个

下拉框第一次会无法选中，可能下拉框选中执行早了

### 期待表现

正常选择

### 运行环境

```markdown
- 浏览器名称：Google Chrome
- 浏览器版本：最新
- 所用用户脚本扩展名称：
- easy-upload版本：最新
```

**Comment by techmovie** [comment]
> 制作组的下拉框是滚动加载，实现有点麻烦，所以先不弄了

应该有个拦截请求的方法 忘了是啥了

**Comment by ted423** [comment]
> > 制作组的下拉框是滚动加载，实现有点麻烦，所以先不弄了
> 
> 应该有个拦截请求的方法 忘了是啥了

我感觉这种下拉框的方式本身有些问题.....特别他们连个按字母排序都没做，所以不如让sysop改

**Comment by ted423** [comment]
Blu-ray会点到UHD Blu-ray

**Comment by ted423** [comment]
无中文的豆瓣外站获取后转会有报错并且没有副标题
