### ISSUE TITLE
[BUG]演唱会转到aither类别填写为music并且不遵循ymal[Done]

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#222]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

测试在填标题之前就选择好了
![image](https://user-images.githubusercontent.com/7042766/218237887-28a9a339-0b97-4328-bf15-f1cdeaa08974.png)

### 期待表现

选到movie

### 运行环境

```markdown
- 浏览器名称：
- 浏览器版本：
- 所用用户脚本扩展名称：
- easy-upload版本：
```

**Comment by ted423** [comment]
原来跟url有关

**Comment by techmovie** [comment]
应该没支持演唱会这个类别

**Comment by ted423** [comment]
不知道是不是写在UploadSiteList里

**Comment by ted423** [comment]
> 应该没支持演唱会这个类别

有支持，不过aither的muisc只是发music
我改了
