### ISSUE TITLE
[BUG]blu的老域名好像确实已经挂了

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#234]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

跟新域名解析ip不一样，无法打开

### 期待表现

完全切换到blutopia.cc

### 运行环境

```markdown
- 浏览器名称：
- 浏览器版本：
- 所用用户脚本扩展名称：
- easy-upload版本：
```

**Comment by techmovie** [comment]
我这里还能打开 但在种子详情页脚本失效了
