### ISSUE TITLE
[新站点]KamePT

### ISSUE THREAD

**Issue by KesaubeEire** [techmovie/easy-upload#236]
### 站点地址

站点地址：https://kamept.com/index.php

### 站点架构

NexusPHP

### 站点是否限制发布权限

否

### 站点发布种子所需的用户等级

User

### 邀请获取渠道

邀请获取渠道 u2猫站有官窑

### 其他

感谢捏

**Comment by KesaubeEire** [comment]
站点已添加

**Comment by akupad** [comment]
有没有邀请码啊第一次接触到私有pt
