### ISSUE TITLE
这段代码bdinfo不工作，u3d和bhd好像都不行

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#286]
https://github.com/techmovie/easy-upload/blob/0d3fa357bfd13810ff05f1873863346e5b6774e7/src/target/bhd.ts#L145

**Comment by ted423** [comment]
发现了，似乎是 Disc Title: 后面跟的空格不一样

**Comment by ted423** [comment]
应该是源站获取时产生的问题

**Comment by ted423** [comment]
https://github.com/techmovie/easy-upload/blob/0d3fa357bfd13810ff05f1873863346e5b6774e7/src/common.ts#L1360

这段代码产生的问题，5个空格变成了3个

**Comment by ted423** [comment]
似乎弄错了，跑到这一步的时候已经是3个空格了

**Comment by ted423** [comment]
三种空格unicode(\u00A0,\u0020,\u3000)
这段代码里删了两种
我把这两个删了？还是说desc里面也删一下？

**Comment by techmovie** [comment]
把\u00A0 \u3000 替换为英文符号的空格比较好 
https://github.com/techmovie/easy-upload/blob/0d3fa357bfd13810ff05f1873863346e5b6774e7/src/common.ts#L1363 也应该改下
