### ISSUE TITLE
[BUG]mtv get torrentfile炸了

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#296]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

```
userscript.html?name…-67aa325c823e:18402 Uncaught (in promise) 
Error: not a number: buffer[0] = 32
    at getIntFromBuffer (userscript.html?name…aa325c823e:18402:13)
    at decode2.buffer (userscript.html?name…aa325c823e:18481:20)
    at decode2.next (userscript.html?name…aa325c823e:18437:24)
    at Object.decode2 [as decode] (userscript.html?name…aa325c823e:18422:20)
    at decodeTorrentFile (userscript.html?name…aa325c823e:18815:33)
    at parseTorrent (userscript.html?name…aa325c823e:18800:20)
    at getTorrentFileData (userscript.html?name…aa325c823e:19037:26)
    at async handleSiteClickEvent (userscript.html?name…aa325c823e:22241:29)
```

看了下selector那步似乎没问题

### 期待表现

。

### 运行环境

```markdown
- 浏览器名称：
- 浏览器版本：
- 所用用户脚本扩展名称：
- easy-upload版本：
```

**Comment by ted423** [comment]
又确认了一下，下种子的连接获取的正常的

**Comment by ted423** [comment]
![image](https://github.com/user-attachments/assets/612564e5-e245-4be9-b0ae-2c52ec02ae48)

**Comment by ted423** [comment]
看起来似乎是因为下了个网页回来

**Comment by ted423** [comment]
![image](https://github.com/user-attachments/assets/0733a8bd-227b-4a70-93ec-2b465d1bc618)

**Comment by techmovie** [comment]
<img width="590" alt="Screenshot 2024-07-23 at 3 09 12 PM" src="https://github.com/user-attachments/assets/01ae76f9-6bbf-4ecd-b574-f61c219bea42">

/torrents.php前面多了一个`/`

**Comment by ted423** [comment]
> <img alt="Screenshot 2024-07-23 at 3 09 12 PM" width="590" src="https://private-user-images.githubusercontent.com/59314774/351221380-01ae76f9-6bbf-4ecd-b574-f61c219bea42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTg5MTAsIm5iZiI6MTcyMTcxODYxMCwicGF0aCI6Ii81OTMxNDc3NC8zNTEyMjEzODAtMDFhZTc2ZjktNmJiZi00ZWNkLWI1NzQtZjYxYzIxOWJlYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjI3ODA2MDE4OThhZmE4NzAzMmY3M2NjYjVmNjVkYWQ4NDA2N2M2YmUzZWRjYWQ3N2Q0YmVlMjkyNzQzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m1iLDaCkdC1sW9mrIP3Qo7BQwihrsZguAtm1uueDwQQ">
> /torrents.php前面多了一个`/`

![image](https://github.com/user-attachments/assets/7d808b45-7174-4129-bcbe-a4e8cc647311)
..................

**Comment by ted423** [comment]
看起来只有mtv中间多了个'/'会跳转，NP是最前面没有‘/’直接'download.php'

**Comment by ted423** [comment]
另外我在想这块要不要做个检测，比如torrentfile 下失败了提示一下，打开新标签页，又或者种子下的时间太长可以手动跳过

**Comment by techmovie** [comment]
可以 如果长时间下载不下来 现在确实有点不太友好
