### ISSUE TITLE
[BUG]豆瓣信息获取问题

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#306]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述
301跳转导致问题
### 期待表现

.

### 运行环境

```markdown
- 浏览器名称：chrome/vivaldi
- 浏览器版本：128
- 所用用户脚本扩展名称：TM
- easy-upload版本：最新
Windows
```

**Comment by ted423** [comment]
UA不影响现象

**Comment by ted423** [comment]
https://movie.douban.com/subject/36205404/
tv还是会400

**Comment by ted423** [comment]
tampermonkey 版本有影响

**Comment by techmovie** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/2179
