### ISSUE TITLE
[BUG]error This project's package.json defines "packageManager": "yarn@4.5.0". However the current global version of Yarn is 1.22.22.

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#313]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

https://github.com/techmovie/easy-upload/blob/b7fab36b638fe0330f3f4364f2fe3e818fd1a07a/package.json#L96

https://stackoverflow.com/questions/78458505/error-this-projects-package-json-defines-packagemanager-yarn3-6-4-howeve

### 期待表现

ubuntu lts 默认好像是 nodejs 18 yarn 1.22.
目前项目好像也没有说推荐的编译环境

### 运行环境

```markdown
- 浏览器名称：
- 浏览器版本：
- 所用用户脚本扩展名称：
- easy-upload版本：
```

**Comment by ted423** [comment]
搞不懂，yarn --version已经是 4.5.1了，install 提示是global 还是 1.22.
目前没查到全局怎么装4.5的

**Comment by ted423** [comment]
新弄了 一台win反而OK，虽然一跑yarn就跑去下东西，但是因为网络问题有可能报错。
但能切到4.5.0

**Comment by techmovie** [comment]
> 搞不懂，yarn --version已经是 4.5.1了，install 提示是global 还是 1.22. 目前没查到全局怎么装4.5的

试试 `corepack enable` 

如果`corepack`命令没有的话 需要单独装一下

**Comment by ted423** [comment]
https://stackoverflow.com/questions/77521525/esbuild-couldnt-be-built-successfully-using-node-v20-yarn-v4-nodelinker-pnpm
install 好像还有个权限问题。

**Comment by ted423** [comment]
```
 YN0060: │ eslint is listed by your project with version 9.13.0 (p9db92), which doesn't satisfy what eslint-config-preact and other dependencies request (^8.57.0).
➤ YN0060: │ eslint-plugin-n is listed by your project with version 17.11.1 (p0ee83), which doesn't satisfy what eslint-config-standard requests (^15.0.0 || ^16.0.0).
➤ YN0060: │ eslint-plugin-promise is listed by your project with version 7.1.0 (p296c9), which doesn't satisfy what eslint-config-standard requests (^6.0.0).
➤ YN0002: │ easy-upload@workspace:. doesn't provide @babel/core (pf603f), requested by @preact/preset-vite.
➤ YN0002: │ easy-upload@workspace:. doesn't provide react (p4588d), requested by sonner.
➤ YN0002: │ easy-upload@workspace:. doesn't provide react-dom (p19efb), requested by sonner.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 577ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.21.5 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-568a720e/build.log)
➤ YN0000: └ Completed in 0s 311ms
➤ YN0000: · Failed with errors in 1s 109ms
```

**Comment by ted423** [comment]
https://github.com/yarnpkg/berry/issues/5344

**Comment by techmovie** [comment]
```
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.13.0 (p9db92), which doesn't satisfy what eslint-config-preact and other dependencies request (^8.57.0).
➤ YN0060: │ eslint-plugin-n is listed by your project with version 17.11.1 (p0ee83), which doesn't satisfy what eslint-config-standard requests (^15.0.0 || ^16.0.0).
➤ YN0060: │ eslint-plugin-promise is listed by your project with version 7.1.0 (p296c9), which doesn't satisfy what eslint-config-standard requests (^6.0.0).
➤ YN0002: │ easy-upload@workspace:. doesn't provide @babel/core (pf603f), requested by @preact/preset-vite.
➤ YN0002: │ easy-upload@workspace:. doesn't provide react (p4588d), requested by sonner.
➤ YN0002: │ easy-upload@workspace:. doesn't provide react-dom (p19efb), requested by sonner.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 613ms
➤ YN0000: ┌ Link step
➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5s 809ms
➤ YN0000: · Done with warnings in 6s 720ms
``` 
看起来像是esbuild的问题

**Comment by ted423** [comment]
> ```
> ➤ YN0000: · Yarn 4.5.0
> ➤ YN0000: ┌ Resolution step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Post-resolution validation
> ➤ YN0060: │ eslint is listed by your project with version 9.13.0 (p9db92), which doesn't satisfy what eslint-config-preact and other dependencies request (^8.57.0).
> ➤ YN0060: │ eslint-plugin-n is listed by your project with version 17.11.1 (p0ee83), which doesn't satisfy what eslint-config-standard requests (^15.0.0 || ^16.0.0).
> ➤ YN0060: │ eslint-plugin-promise is listed by your project with version 7.1.0 (p296c9), which doesn't satisfy what eslint-config-standard requests (^6.0.0).
> ➤ YN0002: │ easy-upload@workspace:. doesn't provide @babel/core (pf603f), requested by @preact/preset-vite.
> ➤ YN0002: │ easy-upload@workspace:. doesn't provide react (p4588d), requested by sonner.
> ➤ YN0002: │ easy-upload@workspace:. doesn't provide react-dom (p19efb), requested by sonner.
> ➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
> ➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed in 0s 613ms
> ➤ YN0000: ┌ Link step
> ➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed
> ➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
> ➤ YN0000: └ Completed in 5s 809ms
> ➤ YN0000: · Done with warnings in 6s 720ms
> ```
> 
> 看起来像是esbuild的问题 对比了一下你的 是最后一步出错了

我试了win ok,ubuntu下我看了上面那个issue都没搞定。esbuild是有执行权限的的，node esbuild --version 直接报错，所以我决定放弃......
删了node_modules 重装也没用
