### ISSUE TITLE
[新站点]

### ISSUE THREAD

**Issue by Gpan666** [techmovie/easy-upload#315]
### 站点地址

https://rousi.zip/

### 站点架构

NexusPHP

### 站点是否限制发布权限

否

### 站点发布种子所需的用户等级

任何人都可以发布

### 邀请获取渠道

邀请注册

**Comment by techmovie** [comment]
站点用的是这里的代码么 https://github.com/xiaomlove/nexusphp

**Comment by techmovie** [comment]
暂不准备支持18+站点
