### ISSUE TITLE
[新站点]似乎还不支持HUNO

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#317]
### 站点地址

hawke.uno

### 站点架构

UNIT3D

### 站点是否限制发布权限

是

### 站点发布种子所需的用户等级
Iron Fleet

### 邀请获取渠道

没注意

### 其他

1

**Comment by techmovie** [comment]
盲写的没测试 可能有bug

**Comment by ted423** [comment]
我本来想有空弄下的，主要是想弄快速搜索
