### ISSUE TITLE
[FEATURE] button to upload screenshots to ptpimg

### ISSUE THREAD

**Issue by Purfview** [techmovie/easy-upload#63]
Script gives errors about ptpimg when you try to transfer an upload which has already ptpimg screenshots (api key not submitted).

Can't ptpimg function be made as button, same as the 'Convert to thumbnails' button function? And some checks added to check if screenshots are already linked from ptpimg.

**Comment by techmovie** [comment]
@Purfview What are the errors about?ptpimg only can get the direct link of the original image,can't get the thumbnais.

**Comment by Purfview** [comment]
Dunno exactly (it's in Chinese and I couldn't copy message from popup), I think something about that it can't upload screens to ptpimg, but I don't want to upload screenshots to ptpimg.

I meant ptpimg function on button (optional) like other buttons, not about thumbnails.
If I'm not mistaken ptpimg fuction uploads screenshots to ptpimg host!?

**Comment by techmovie** [comment]
@Purfview ptpimg function is only used on bB and its to change the image host of the poster.cuz bB is only allowed a few imagehost ,like ptpimage,imgur.

**Comment by Purfview** [comment]
Yeap, I used bB as a target site. Ah, I thought that it wants to upload screenshots, now I'll know.

Anyway, a button to transfer screenshots to ptpimg would be a good feature (no need for thumbnails).

**Comment by techmovie** [comment]
closes in https://github.com/techmovie/easy-upload/commit/ced863ccfc658493a28589a21e2c0b113e54b113
