### ISSUE TITLE
[新站点] TeamHD

### ISSUE THREAD

**Issue by dibin666** [techmovie/easy-upload#71]
* 站点地址：https://teamhd.org/
* 站点架构：unknown
* 站点是否限制发布权限：是
* 站点发布种子所需的用户等级：非管理允许不能发布
* 邀请获取渠道：HDHome LemonHD BTSCHOOL等站点官窑
* 其他信息：支持转载到其他站和自动获取豆瓣信息即可

**Comment by techmovie** [comment]
提供下上传页和种子详情页的html文件吧

**Comment by dibin666** [comment]
> 提供下上传页和种子详情页的html文件吧

要怎么提取

**Comment by techmovie** [comment]
@dibin666 右键 另存为。存好后用编辑器打开看下有没有个人信息。

**Comment by dibin666** [comment]
> @dibin666 右键 另存为。存好后用编辑器打开看下有没有个人信息。

**Comment by dibin666** [comment]
> > @dibin666 右键 另存为。存好后用编辑器打开看下有没有个人信息。

https://drive.google.com/drive/folders/1Z0iVsW7CO3D6AynRdGYGMt2WADvOi310?usp=sharing
