### ISSUE TITLE
[FEATURE] 从堡转出时检测所用图床是否为堡的内部图床

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-upload#75]
**这个功能是否与某个问题相关**
堡的内部图床不允许游客访问

**描述你的期望功能**
从堡转出资源时，自动检测图片是否托管在堡的内部图床，如果是的话可以像禁转一样弹出提示框。

**描述你的替代方案**
无

**额外信息**
无

**Comment by techmovie** [comment]
@scatking 这个我也注意到了，考虑先把图片转成base64然后再转存到别的图床。
