### ISSUE TITLE
[FEATURE] 目标站点为PTer时，优化mediainfo bbcode

### ISSUE THREAD

**Issue by scatking** [techmovie/easy-upload#78]
**这个功能是否与某个问题相关**
PTer有 mediainfo 和bdinfo parser

**描述你的期望功能**
当目标站点为PTer时，如果源站点有完整mediainfo/bdinfo，可以使用[hide=mediainfo][/hide] / [hide=BDInfo][/hide]的bbcode来美化显示相关信息。

**描述你的替代方案**

**额外信息**
* [hide=mediainfo][/hide] 演示
![](https://i.ibb.co/gFj4MGQ/Snipaste-2021-05-11-13-00-55.png)
* [hide=BDInfo][/hide] 演示
![](https://i.ibb.co/KbPc9M3/Snipaste-2021-05-11-13-01-38.png)

**Comment by techmovie** [comment]
看你的repo也有开发猫的一些脚本，可以考虑提个PR😜

**Comment by techmovie** [comment]
哈哈 好吧 我尽量多写点注释
