### ISSUE TITLE
[FEATURE]通过点击[快速检索]字样进行快速检测是否目标站有当前种子

### ISSUE THREAD

**Issue by kidgokugoku** [techmovie/easy-upload#79]
**这个功能是否与某个问题相关**

**描述你的期望功能**
通过点击[快速检索]字样进行快速检测是否目标站有当前种子。
![动画](https://user-images.githubusercontent.com/82298915/117905146-45ab6180-b305-11eb-92a8-8248df0c7083.gif)
实现类似上图的效果，点击前站点标签为黑色，有相同内容（imdbid | doubanid）显示红色，有重复种子显示蓝色。（或其他颜色方案可以留给用户自定义？）
点击红色或黑色标签将打开搜索页面，点击蓝色标签将自动打开重复种子页面（可能多个）。
如果检测到了重复种子则在批量转种时屏蔽对应站点。
**描述你的替代方案**

**额外信息**
通过实现这个功能可以快速判断当前下载的种子能否辅种和能否转种。

**Comment by techmovie** [comment]
https://github.com/techmovie/easy-upload/commit/116c385ffd088cc9f207b85da669d305ed8e0365

仅支持NexusPHP站点，其余站点不准备支持了。
