### ISSUE TITLE
[New Site] SC

### ISSUE THREAD

**Issue by Purfview** [techmovie/easy-upload#82]
* URL： https://secret-cinema.pw
* Site based on Gazelle
SC as target and source site. It's similar to PTP.  I can provide an invite.

**Comment by Purfview** [comment]
Thanks, I'll test it.
I see it didn't auto filled English title.  At "Movie title" field goes original title like "Qiuqiu ni, biaoyang wo", at "Alternate title" should go English title like "Gimme Kudos". 

I'm thinking isn't somehow possible to auto fetch torrent files too? Because SC site can take any torrent file from other tracker and it auto transforms it by changing "Source" to SC in the torrent file to change hash.

**Comment by Purfview** [comment]
"Quick search" is not searching by imdb id. URL to search by id: https://secret-cinema.pw/torrents.php?cataloguenumber=tt8772262

**Comment by Purfview** [comment]
Icon is bigger than the other icons:
![alt text](https://i.imgur.com/Qt076wo.png)

**Comment by Purfview** [comment]
Now I tried to transfer but script doesn't fill anything, tried from PTP and KG. I see stuff in the URL but nothing is filled.

**Comment by techmovie** [comment]
> Now I tried to transfer but script doesn't fill anything, tried from PTP and KG. I see stuff in the URL but nothing is filled.

Firefox?



> I'm thinking isn't somehow possible to auto fetch torrent files too? Because SC site can take any torrent file from other tracker and it auto transforms it by changing "Source" to SC in the torrent file to change hash.

That's can't be done

**Comment by Purfview** [comment]
> Firefox?

Waterfox Classic, it's based on  Firefox.
Nothing unusual in browser's console.

**Comment by Purfview** [comment]
I looked at code, I think problem is new JS optional chaining "?." in`sc.js`, few lines like with "imdbData?.details?" and "?.[1]".

It's better to refrain from very new JS methods, as it drastically narrows compatibility.

**Comment by techmovie** [comment]
@Purfview you can check the dist file,which is transformeb

**Comment by Purfview** [comment]
Ah, syntax is transformed in dist, then I dunno where problem is.

**Comment by techmovie** [comment]
> Ah, syntax is transformed in dist, then I dunno where problem is.

G3.2.3 (64-bit) MacOS works fine.

**Comment by Purfview** [comment]
Can you make a script with `console.log` at some points to debug and upload it as a test branch?

**Comment by techmovie** [comment]
You can leave your following information:
* Operating system: 
* Browser：
* Browser Version ：
* Script manager extension[e.g. tampermonkey Violentmonkey]：

**Comment by techmovie** [comment]
Can't reproduce.Closed for now.
