### ISSUE TITLE
[New Site] PTN tracker support request

### ISSUE THREAD

**Issue by gitgudh** [techmovie/easy-upload#98]
* URL：https://piratethenet.org/
* Site based on[e.g. Gazelle UNIT3D]：idk
* Whether the site restricts publishing rights：no
* The user level required for the site to publish new torrent：any user can
* Where to get an invite：from me, i've sent a PM to you at PTP recently
 ok what's your Telegram ID?
* Additional text：
Thanks!

**Comment by gitgudh** [comment]
@OParham 
my Telegram ID o/

**Comment by ted423** [comment]
@gitgudh EasyUpload PT转种交流
https://t.me/easyupload
